### ISSUE TITLE
Uncaught thread exception on channel 997/998

### ISSUE THREAD

**Issue by Polderdijk** [Sholofly/ZiggoNext#59]
When changing channel to 997 or 998 a Uncaught thread exception fires and the component frees.

Logger: root
Source: /usr/src/homeassistant/homeassistant/bootstrap.py:318
First occurred: 12:27:46 (1 occurrences)
Last logged: 12:27:46
Uncaught thread exception

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 225, in _on_mqtt_client_message
    self.settop_boxes[deviceId].update_settop_box(jsonPayload)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonextbox.py", line 186, in update_settop_box
    channel = self.channels[channelId]
KeyError: 'NL_000181_019669'

Channel 997 (Testbeeld)
Also on channel 998 (Zenderoverzicht): NL_000182_019349

**Comment by Sholofly** [comment]
Should be fixed. Please let me know your findings!

**Comment by Polderdijk** [comment]
> Should be fixed. Please let me know your findings!

I update and tested it, but the same error, but on line 187.

If i can provide you with more info, please let me known.

**Comment by ashmodai6** [comment]
Actually for me not fixed either ...

Le mar. 22 déc. 2020 à 19:03, Polderdijk <notifications@github.com> a
écrit :

**Comment by Sholofly** [comment]
You guys were right. There was still an issue. Its fixed now.
